"""Add level and stream to class and status to exam

Revision ID: 812e0fe6b70f
Revises: f8ac5b418d3d
Create Date: 2026-07-22 16:30:28.834059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812e0fe6b70f'
down_revision: Union[str, None] = 'f8ac5b418d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add level as nullable first
    op.add_column('class', sa.Column('level', sa.String(), nullable=True))
    op.add_column('class', sa.Column('stream', sa.String(), nullable=True))
    
    # 2. Populate level from existing name column if present
    op.execute("UPDATE class SET level = COALESCE(name, 'S.1') WHERE level IS NULL")
    
    # 3. Alter level to NOT NULL
    op.alter_column('class', 'level', nullable=False)
    
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.create_index(op.f('ix_class_level'), 'class', ['level'], unique=False)
    op.drop_column('class', 'name')
    
    # 4. Create Enum and Add status to exam with default 'OPEN'
    exam_status_enum = sa.Enum('OPEN', 'SEALED', name='examstatus')
    exam_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('exam', sa.Column('status', exam_status_enum, server_default='OPEN', nullable=False))
    op.alter_column('exam', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exam', 'status')
    op.add_column('class', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_class_level'), table_name='class')
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=False)
    op.drop_column('class', 'stream')
    op.drop_column('class', 'level')
    # ### end Alembic commands ###
