"""Add file_hash to submission table

Revision ID: e42b30f75721
Revises: 812e0fe6b70f
Create Date: 2026-07-22 16:46:33.641825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42b30f75721'
down_revision: Union[str, None] = '812e0fe6b70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_submission_file_hash'), 'submission', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_file_hash'), table_name='submission')
    op.drop_column('submission', 'file_hash')
    # ### end Alembic commands ###
