"""Add exam metadata fields

Revision ID: f8ac5b418d3d
Revises: 2f16f933e781
Create Date: 2026-07-07 11:39:25.932957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ac5b418d3d'
down_revision: Union[str, None] = '2f16f933e781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('exam_type_id', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('term', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'year')
    op.drop_column('exam', 'term')
    op.drop_column('exam', 'exam_type_id')
    op.drop_column('exam', 'subject_id')
    # ### end Alembic commands ###
